language: node_js
node_js:
  - "stable"
branches:
  only:
    - deploy
after_success:
  - bash scripts/deploy.sh
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $Git_Token
  keep_history: true
  on:
    branch: deploy
